# Generated by Django 5.0.6 on 2024-06-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('cupon', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('url', models.URLField()),
                ('description', models.CharField(max_length=250)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='travels/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='posts_trave_created_78add4_idx')],
            },
        ),
    ]
