# Generated by Django 5.0.6 on 2024-07-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='status',
            field=models.CharField(choices=[('AC', 'Active'), ('DS', 'Disable'), ('CN', 'Cancelled')], default='AC', max_length=20),
        ),
    ]
