# Generated by Django 5.0.7 on 2024-07-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_travelpost_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
