# Generated by Django 5.0.7 on 2024-07-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_travelpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='detail_description',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='description',
            field=models.CharField(max_length=2500),
        ),
    ]
