# Generated by Django 5.0.7 on 2024-07-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_travelpost_detail_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='detail_description',
            field=models.CharField(default='welcome', max_length=400),
        ),
    ]
