# Generated by Django 5.0.7 on 2024-07-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_travelpost_detail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='detail_description',
            field=models.CharField(max_length=400),
        ),
    ]
