# Generated by Django 5.0.7 on 2024-07-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_travelpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='travelpost',
            name='photo',
            field=models.ImageField(null=True, upload_to='travels/%Y/%m/%d/'),
        ),
    ]
