# Generated by Django 5.0.7 on 2024-07-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_travelpost_updated_alter_travelpost_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
