# Generated by Django 5.0.7 on 2024-07-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_travelpost_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpost',
            name='category',
            field=models.CharField(choices=[('FL', 'Vuelos'), ('FH', 'Vuelos y Hotel'), ('AC', 'Alojamiento'), ('CR', 'Cruceros')], default='FL', max_length=2),
        ),
    ]
