# Generated by Django 5.0.7 on 2024-07-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_travelpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelpost',
            name='category',
            field=models.CharField(choices=[('FL', 'Vuelos'), ('FH', 'Vuelos y Hotel'), ('AC', 'Alojamiento'), ('CR', 'Cruceros')], default='FL', max_length=20),
        ),
    ]
